/**
 * -- DO NOT EDIT THIS FILE --
 * This file is generated automatically during the build process
 * (./configure && make) based on the standard GNU Auto-tools.
 */
package jp.osdn.korenani;

public interface Version {

    public String versionString = "Korenani 0.1";

}
